
import '../../../dummymodels/estimate_model.dart';

final List<EstimateModel> dummyQuotations = [
  EstimateModel(
    id: 'EsNo.001',
    contractorName: 'Greenfield Developers',
    siteAddress: 'Calicut, Kerala',
    phone: '+91 65432 10987',
    salesmanName: 'Rahul Kumar',
    salesmanMobile: '+91 90000 11122',
    date: DateTime(2025, 5, 17),
    status: 'Draft',
    billType: EstimateBillType.quotation,
    handlingCharge: 500,
    items: const [
      EstimateItem(
        id: 'i1',
        name: 'Marval Satuario',
        company: 'Somany',
        size: '600x1200',
        unit: 'sqrft',
        quantity: 1000,
        mrp: 80,
        rate: 60,
      ),
      EstimateItem(
        id: 'i2',
        name: 'Sanitary Ware',
        company: 'Hindware',
        size: '-',
        unit: 'sets',
        quantity: 10,
        mrp: 4500,
        rate: 3500,
      ),
    ],
  ),
  EstimateModel(
    id: 'EsNo.002',
    contractorName: 'Nila Constructions',
    siteAddress: 'Thrissur, Kerala',
    phone: '+91 99887 66554',
    salesmanName: 'Rahul Kumar',
    salesmanMobile: '+91 90000 11122',
    date: DateTime(2025, 5, 14),
    status: 'Draft',
    billType: EstimateBillType.quotation,
    handlingCharge: 0,
    items: const [
      EstimateItem(
        id: 'i1',
        name: 'Vitrified Tile',
        company: 'Kajaria',
        size: '800x800',
        unit: 'sqrft',
        quantity: 600,
        mrp: 65,
        rate: 48,
      ),
    ],
  ),
  EstimateModel(
    id: 'EsNo.003',
    contractorName: 'Coastal Builders',
    siteAddress: 'Alappuzha, Kerala',
    phone: '+91 91234 56789',
    salesmanName: 'Rahul Kumar',
    salesmanMobile: '+91 90000 11122',
    date: DateTime(2025, 5, 10),
    status: 'Draft',
    billType: EstimateBillType.quotation,
    handlingCharge: 1200,
    items: const [
      EstimateItem(
        id: 'i1',
        name: 'Marval Satuario',
        company: 'Somany',
        size: '600x1200',
        unit: 'sqrft',
        quantity: 400,
        mrp: 80,
        rate: 62,
      ),
      EstimateItem(
        id: 'i2',
        name: 'Wall Putty',
        company: 'Birla',
        size: '-',
        unit: 'bags',
        quantity: 25,
        mrp: 550,
        rate: 480,
      ),
      EstimateItem(
        id: 'i3',
        name: 'Sanitary Ware',
        company: 'Hindware',
        size: '-',
        unit: 'sets',
        quantity: 4,
        mrp: 4500,
        rate: 3500,
      ),
    ],
  ),
];